# Generated by Django 3.2.11 on 2022-02-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nm_variavel', max_length=255)),
                ('identificador', models.CharField(db_column='nm_identificador', max_length=50)),
                ('unidade', models.CharField(blank=True, db_column='nm_unidade', max_length=10, null=True)),
                ('calculadora', models.ForeignKey(db_column='cd_calculadora', on_delete=django.db.models.deletion.CASCADE, related_name='variaveis', to='calculadora.calculadora')),
            ],
            options={
                'verbose_name': 'Variavel',
            },
        ),
    ]
